apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: test-appset
spec:
  test:
    enable: true
  rollback:
    enable: true
  chart:
    repository: https://takutakahashi.github.io/charts
    version: 0.2.4
    name: appset
  values:
    api:
      image: nginx
      revision: latest
    frontend:
      image: nginx
      revision: takutakahashi
