app:
  image: "nginx"
  livenessProbe:
    httpGet:
      path: /
      port: 80
  readinessProbe:
    httpGet:
      path: /
      port: 80

service:
  port: 80

litestream:
  image: "litestream/litestream:latest"
  dbPath: "/data/app.db"
  replica:
    uri: "gcs://test/backup/app.db"
    region: "asia-northeast1"
  encryption: false
  secretKeyName: "test-key"

